name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Copy files to the EC2 instance
          scp -o StrictHostKeyChecking=no -r . $EC2_USER@$EC2_HOST:~/app

          # SSH into EC2 and set up the app
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/app

            # Install Python dependencies
            pip install -r requirements.txt

            # Apply database migrations
            python3 manage.py migrate

            # Start or reload the Django app with PM2
            pm2 start "python3 manage.py runserver 0.0.0.0:8000" --name "pygoat" || pm2 reload "pygoat"

            # Save the PM2 process list for persistence
            pm2 save
          EOF
