name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # SSH into EC2 and pull the latest code
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/app

            # Pull the latest changes from the main branch
            git pull origin main

            # Activate the virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Apply database migrations
            python3 manage.py migrate

            # Start or reload the app with PM2
            pm2 start "venv/bin/python3 manage.py runserver 0.0.0.0:8000" --name "pygoat" || pm2 reload "pygoat"

            # Save the PM2 process list for persistence
            pm2 save
          EOF
